# Generated by Django 4.0.3 on 2022-04-14 14:59

import User_Management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential_Details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, validators=[User_Management.models.isValid_contactNo])),
                ('password', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credential_details',
            },
        ),
        migrations.CreateModel(
            name='userDetails_hist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50, validators=[User_Management.models.isValid_gender])),
                ('email_id', models.EmailField(max_length=254, validators=[User_Management.models.isValid_email])),
                ('address', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
                ('hist_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details_hist',
            },
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50, validators=[User_Management.models.isValid_gender])),
                ('email_id', models.EmailField(max_length=254, validators=[User_Management.models.isValid_email])),
                ('address', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='Credential_Details_hist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('hist_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Management.Credential_Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credential_details_hist',
            },
        ),
    ]
