# Generated by Django 4.0.3 on 2022-04-19 12:20

import User_Management.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential_details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='Staff_Details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50, validators=[User_Management.models.isValid_gender])),
                ('email_id', models.EmailField(max_length=254, validators=[User_Management.models.isValid_email])),
                ('address', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'staff_details',
            },
        ),
    ]
