# Generated by Django 4.0.3 on 2022-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_alter_credential_details_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_details',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='staff_details',
            old_name='address',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='staff_details',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='staff_details',
            name='date',
        ),
        migrations.RemoveField(
            model_name='staff_details',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff_details',
            name='user_id',
        ),
        migrations.AddField(
            model_name='staff_details',
            name='username',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='staff_details',
            table='User',
        ),
    ]
