# Generated by Django 4.0.3 on 2022-04-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0003_rename_email_id_staff_details_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff_details',
            table='staff_details',
        ),
    ]
