# Generated by Django 4.0.3 on 2022-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0004_alter_staff_details_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_details',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
