# Generated by Django 4.0.3 on 2022-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='unit',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
